import { Injector, OnInit, OnDestroy, DoCheck, ElementRef } from '@angular/core';
import { ControlValueAccessor, NgControl } from '@angular/forms';
import { FocusMonitor } from '@angular/cdk/a11y';
import { MatFormFieldControl } from '@angular/material/form-field';
import { Subject } from 'rxjs';
export declare class CcDateComponent implements OnInit, OnDestroy, DoCheck, ControlValueAccessor, MatFormFieldControl<CcDateComponent> {
    private injector;
    private elRef;
    private fm;
    static nextId: number;
    styleClass: string;
    value: any;
    placeholder: string;
    readonly empty: boolean;
    required: boolean;
    disabled: boolean;
    defaultStyles: any;
    private _value;
    private _placeholder;
    private _disabled;
    private _defaultStyles;
    private _required;
    ngControl: NgControl;
    focused: boolean;
    errorState: boolean;
    stateChanges: Subject<void>;
    cardDate: string;
    onChanges: any;
    onTouched: any;
    id: string;
    describedBy: string;
    readonly shouldLabelFloat: boolean;
    constructor(injector: Injector, elRef: ElementRef<HTMLElement>, fm: FocusMonitor);
    ngOnInit(): void;
    ngDoCheck(): void;
    writeValue(val: string): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDescribedByIds(ids: string[]): void;
    onContainerClick(event: MouseEvent): void;
    updateDate(): void;
    updateOnTouch(): void;
    ngOnDestroy(): void;
}
