import { Injector, OnInit, OnDestroy, DoCheck, ElementRef } from '@angular/core';
import { ControlValueAccessor, NgControl, AbstractControl, ValidationErrors, NgForm, FormGroupDirective } from '@angular/forms';
import { FocusMonitor } from '@angular/cdk/a11y';
import { ErrorStateMatcher } from '@angular/material/core';
import { MatFormFieldControl } from '@angular/material/form-field';
import { Subject } from 'rxjs';
export declare class CcCvvComponent implements OnInit, OnDestroy, DoCheck, ControlValueAccessor, MatFormFieldControl<CcCvvComponent> {
    private injector;
    private elRef;
    private fm;
    private parentForm;
    private parentFormGroup;
    private defaultErrorStateMatcher;
    static nextId: number;
    styleClass: string;
    value: any;
    placeholder: string;
    readonly empty: boolean;
    required: boolean;
    disabled: boolean;
    defaultStyles: any;
    cvvSize: number;
    private _value;
    private _placeholder;
    private _disabled;
    private _defaultStyles;
    private _required;
    private _cvvSize;
    private _formSubmitSubscription;
    ngControl: NgControl;
    focused: boolean;
    errorState: boolean;
    stateChanges: Subject<void>;
    cardCvv: string;
    onChanges: any;
    onTouched: any;
    maxCvvLength: number;
    id: string;
    describedBy: string;
    readonly shouldLabelFloat: boolean;
    constructor(injector: Injector, elRef: ElementRef<HTMLElement>, fm: FocusMonitor, parentForm: NgForm, parentFormGroup: FormGroupDirective, defaultErrorStateMatcher: ErrorStateMatcher);
    ngOnInit(): void;
    ngDoCheck(): void;
    validate(control: AbstractControl): ValidationErrors | null;
    writeValue(val: string): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDescribedByIds(ids: string[]): void;
    onContainerClick(event: MouseEvent): void;
    updateCvv(event: Event): void;
    updateOnTouch(): void;
    ngOnDestroy(): void;
    updateErrorState(): void;
}
