import { Injector, OnInit, OnDestroy, DoCheck, ElementRef } from '@angular/core';
import { FocusMonitor } from '@angular/cdk/a11y';
import { ControlValueAccessor, NgControl, NgForm, FormGroupDirective } from '@angular/forms';
import { ErrorStateMatcher } from '@angular/material/core';
import { MatFormFieldControl } from '@angular/material/form-field';
import { Subject } from 'rxjs';
import { NgxCcService } from './ngx-cc.service';
import { CardConfig } from './ngx-cc.model';
import { CardIcons } from './ngx-cc.config';
export declare class NgxCcComponent implements OnInit, OnDestroy, DoCheck, ControlValueAccessor, MatFormFieldControl<NgxCcComponent> {
    private injector;
    private elRef;
    private fm;
    private parentForm;
    private parentFormGroup;
    private defaultErrorStateMatcher;
    private creditCardService;
    private ccCardIcons;
    static nextId: number;
    styleClass: string;
    get value(): any;
    set value(cardNumber: any);
    get placeholder(): string;
    set placeholder(placeholder: string);
    get empty(): boolean;
    get required(): boolean;
    set required(req: boolean);
    get disabled(): boolean;
    set disabled(dis: boolean);
    get defaultStyles(): any;
    set defaultStyles(val: any);
    private _value;
    private _placeholder;
    private _disabled;
    private _defaultStyles;
    private _required;
    private _formSubmitSubscription;
    private _cardIcons;
    ngControl: NgControl;
    focused: boolean;
    errorState: boolean;
    cardNumber: string;
    cardIcon: string;
    card: CardConfig;
    onChange: any;
    onTouched: any;
    stateChanges: Subject<void>;
    maxNumberLimit: number;
    id: string;
    describedBy: string;
    get shouldLabelFloat(): boolean;
    constructor(injector: Injector, elRef: ElementRef<HTMLElement>, fm: FocusMonitor, parentForm: NgForm, parentFormGroup: FormGroupDirective, defaultErrorStateMatcher: ErrorStateMatcher, creditCardService: NgxCcService, ccCardIcons: CardIcons);
    ngOnInit(): void;
    ngDoCheck(): void;
    writeValue(value: string): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDescribedByIds(ids: string[]): void;
    onContainerClick(event: MouseEvent): void;
    updateIcon(event: Event): void;
    updateOnTouch(): void;
    ngOnDestroy(): void;
    updateErrorState(): void;
}
